[package]
name = "my_todo_list"
version = "1.0.0"
authors = []

[addresses]
todolist_addr='c0910143714a05b5acf337081d3f073fe13803dca207061a46e8a94f10a7b72c'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
